algoritmo "Escreva um algoritmo que leia um número informados pelo usuário e exiba se ele é par ou ímpar."
// Função :
// Autor : João Pedro Nery
// Data : 05/03/2025
// Seção de Declarações 
var

numero: inteiro

inicio
// Seção de Comandos 

escreval("Digite um número inteiro qualquer:")
leia (numero)

se   numero %2 = 0 entao
escreval("O número" ,numero, " é par!")

senao
escreval("O número" ,numero," é impar!")

fimse
fimalgoritmo
